#!/usr/bin/env php
<?php
/**
 * PHPLame by Alex Litvinok
 */

define( 'PHPLAME_HOME', dirname(__FILE__) );
define( 'PHPLAME_VERSION', 'dev' );

require_once( PHPLAME_HOME.'/lib/autoload.php' );

new PHPLameSuite( array_pop($argv), getopt('', array(
    'junit::',
    'json::',
    'tags::',
    'bootstrap::',
    'debug:',
    'silent:',
    'verbose:',
    'nocolor:',
    'average:',
    'time:'
)));