#!/usr/bin/env php
<?php
/**
 * PHPLame by Alex Litvinok
 */

define( 'PHPLAME_HOME', dirname(__FILE__) );
define( 'PHPLAME_VERSION', 'dev' );

require_once( PHPLAME_HOME.'/lib/autoload.php' );

// Get user options
$options_config = array();
$options_user = getopt('c:', array(
               'junit::',
               'json::',
               'tags::',
               'bootstrap::',
               'debug:',
               'silent:',
               'verbose:',
               'nocolor:',
               'average:',
               'time:',
               'config:'
));


// Prepare config file name for parse it
if ( is_set($options_user['c']) ) $file_config = $options_user['c'];
elseif ( is_set($options_user['config']) ) $file_config = $options_user['config'];
else $file_config = './phplame.json';

// Parse config
if ( is_file($file_config) ) $options_config = json_decode( file_get_contents( $file_config ), true );

// Start tests
new PHPLameSuite( array_pop($argv), array_merge( $options_user, $options_config ) );